FROM python:3.10-alpine

LABEL maintainer="saulyaka"

ENV PYTHONUNBUFFERED 1

WORKDIR /code
COPY requirements_test.txt requirements_test.txt

RUN pip install --upgrade pip && \
    pip install -r requirements_test.txt

COPY ./pleinr code
