version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
    - db.env

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: dev.env
    volumes:
      - ./pleinr:/code
      - ./static:/static
      - ./media:/media
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py wait_for_db && 
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  db_data:

